### ISSUE TITLE
Compute TOT for FORESCE

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#101]
We currently have CAT-equivalent data for FORESCE (a value for each PRMS segment). To get a value corresponding to the total upstream area (TOT):

1. Match the `hru_segment` column to the `subseg_seg` column in `p1_prms_reach_attr`
2. For each `subseg_seg`, get all upstream `subseg_seg` values by recursively checking the `from` column in `p1_prms_reach_attr`. That results in a vector of all `subseg_seg` that are upstream of the current `subseg_seg`.
3. Compute the TOT value for the `subseg_seg` by taking the area-weighted sum of the CAT values in each upstream segment.

**Comment by msleckman** [comment]
Looking for some help thinking through this problem: 

My steps to address issue above are the following: 

There are two relevant target dfs for this process: 

1. `p1_prms_reach_attr` which conveniently maps the immediate upstream source segment(s) `from_segs` and the downstream segment `to_seg` of each prms segment (`subseg_id`) . (Note that there are sometimes multiple `from_segs` - addressed in step 1 below.)
```
p1_prms_reach_attr %>% dplyr::select(subseg_id,subseg_seg,from_segs,to_seg)
# A tibble: 456 × 4
   subseg_id subseg_seg from_segs to_seg
   <chr>          <dbl> <chr>      <dbl>
 1 1_1                1 NA             3
 2 2_1                2 NA             8
 3 3_2                3 8              4
 4 4_1                4 3              5
 5 5_1                5 4;9           11
 6 6_1                6 NA            13
 [...]
 ```
 2. `p2_FORESCE_LC_per_catchment_reclass` which has the proportion of LC Class (standardized w/ NLCD classes) per PRMS id (`PRMS_segid`)and `hru_segment` (which matches `subseg_seg` above
```
p2_FORESCE_LC_per_catchment_reclass[[1]]
# A tibble: 418 × 14
   PRMS_segid hru_segment total_PRMS_area prop_lcClass_3 prop_lcClass_2 prop_lcClass_1
   <chr>            <int>           <dbl>          <dbl>          <dbl>          <dbl>
 1 1_1                  1          15774.         0.184         0.00809       0.00206 
 2 2_1                  2          30180.         0.0685        0.00823       0.000582
 3 3_1                  3          38735.         0.177         0.0139        0.00148 
 4 3_2                  3          38735.         0.177         0.0139        0.00148 
 
[...]
```

**The processing steps are the following:**
1. separate `p1_prms_reach_attr$from_segs` to have a unique row for each `from_segs` value - _done_
e.g. 
```
> ## separate fro_segs into new rows (no more ; sep from segs)
> p1_prms_reach_attr %>% dplyr::select(subseg_id,subseg_seg,from_segs,to_seg) %>% 
+     tidyr::separate_rows(from_segs,sep=";")
# A tibble: 561 × 4
   subseg_id subseg_seg from_segs to_seg
   <chr>          <dbl> <chr>      <dbl>
 1 1_1                1 NA             3
 2 2_1                2 NA             8
 3 3_2                3 8              4
 4 4_1                4 3              5
 5 5_1                5 4             11
 6 5_1                5 9             11
 7 6_1                6 NA            13
 8 7_1                7 NA            12
 9 8_2                8 2              3
```

2. Create a new col ` p1_prms_reach_attr$all_from_segs` populated with a vector of all upstream segments (`from_segs`) of each segment (^ comment above describes recursive function to do this). - _stuck_
3. Run `separate_rows()` again on the new col to have a new row for each value in `all_from_segs` - _to do_
4. Merge new vrsn of `p1_prms_reach_attr` with `p2_FORESCE_LC_per_catchment_reclass` by `c(subseg_id == PRMS_segid)` - _to do_
5. Run a group_by on merged df by `PRMS_segid` and summarize across all `prop_lcClass` values, calculating the area-weighted sum. This will give the proportion of each LC class for all upstream catchments of each PRMS segment  - _to do_

In ** step 2** +, how do I extract all correct `from_segs` associated with each `$subseg_id` when some segments have multiple `from_segs` (ex: `5_1`). Please see gist and comment on code there. 
See [gist](https://gist.github.com/msleckman/f9503d896c79753f5bbd09bf2cb65da7)

Current outcome of recursive function in image below. Note the error in `$all_from_segs` for duplicate `$subseg_id` (e.g. when `reach_attr_table$subseg_id == 5_1` & `reach_attr_table$from_segs == 9`, its `reach_attr_table$all_from_segs` vector starts with `4`). 

![image](https://user-images.githubusercontent.com/36547359/156620013-259d9ed9-4ed1-4c2c-bf50-27a74a3aa3e7.png)

**Comment by jds485** [comment]
> 1. separate p1_prms_reach_attr$from_segs to have a unique row for each from_segs value

Instead of making a new row for each from_segs value, would it help to change the format of the `from_segs` column to be a vector of the segment values?

**Comment by lekoenig** [comment]
Thanks for looking into this, @msleckman! During our meeting today I mentioned that another approach to this problem might be to use the crosswalk table to take advantage of functions within `nhdplusTools` that identify upstream tributaries. I haven't tested it, but I think something like this would work, for example:

```
# create another 'target' for the comid_segs; 
# what comid's intersect PRMS segments?
drb_comids_seg <- p2_prms_nhdv2_xwalk %>%
  select(PRMS_segid, comid_seg) %>% 
  tidyr::separate_rows(comid_seg,sep=";") %>% 
  rename(comid = comid_seg)

# Define function to return PRMS segs upstream of a given PRMS seg_id
get_upstream_prms_segs <- function(prms_line,nhd_lines,downstream_comids,segment_comids){
  
  # Filter downstream_comids to only include the PRMS subsegid of interest
  comid_down <- downstream_comids %>%
    filter(PRMS_segid %in% prms_line$subsegid)
  
  # Use nhdplusTools to find all COMIDs upstream of comid_down
  comids_UT <- nhdplusTools::get_UT(network = p1_nhdv2reaches_sf,
                                    comid = comid_down$comid,
                                    # set distance (km) at some arbitrary high value
                                    distance = 2000)
  
  # From the COMIDs that intersect PRMS segments, retain those COMIDs 
  # that are upstream of comid_down
  PRMS_segs_upstream <- segment_comids %>%
    filter(comid %in% comids_UT) %>%
    pull(PRMS_segid)
  
 return(PRMS_segs_upstream)
  
}


# function returns upstream segs for one PRMS segment (x); lapply/map
# over get_upstream_prms_segs for each seg within PRMS network
x <- p1_reaches_sf[1,]
upstream_segs <- get_upstream_prms_segs(prms_line = x,
                              nhd_lines = p1_nhdv2reaches_sf,
                              downstream_comids = p2_drb_comids_down,
                              segment_comids = drb_comids_seg)

```

**Comment by msleckman** [comment]
Will have to look at this Lauren as I am more deep into the recursive approach we've worked on earlier. 

@jds485  realizing we'll need to add the current `reach_attr_table$subseg_seg` to the list in `reach_attr_table$subseg_seg` otherwise we are missing the area of the CAT.

**Comment by jds485** [comment]
> realizing we'll need to add the current reach_attr_table$subseg_seg to the list in reach_attr_table$subseg_seg otherwise we are missing the area of the CAT

Yes, I figured that would happen after gathering all of the upstream HRUs with the gist function. If you think it's simpler to also return the current HRU, I can suggest a way to do that within the function

**Comment by msleckman** [comment]
Commit https://github.com/USGS-R/drb-inland-salinity-ml/pull/97/commits/b233aef84a8a2ce0ae8dc93147e404d90bad998d adds this to the pipeline. 

One stand-alone function was added `recursive_fun()` and the rest of the calculation was done in the same pipe in 2_process.R. We can later put this into a function but prioritizing other the remains blocks to resolve this issue. 

Remaining problems: 

1. Not all upstream are being captured at the moment. Issue noted in [gist](https://gist.github.com/msleckman/f9503d896c79753f5bbd09bf2cb65da7). 
2. `hru_area` is used to aggregate metrics to PRMS scale. [2_process.R L:155](https://github.com/USGS-R/drb-inland-salinity-ml/pull/97/files#diff-63ccbed267aba1bed82a40e026e3a042c216fdc5a500ce3cdb9ddab1fc422995R155) ( Given @lekoenig 's review of the NHD metadata, this needs to be updated (although this may automatically change when we use the updated catchments gpckg for the land cover processing.
