### ISSUE TITLE
Combine NLCD and FORESCE data

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#102]
Create timeseries of the FORESCE and NLCD datasets for each PRMS segment

**Comment by jds485** [comment]
@msleckman: do you want to handle this issue and linked issues? Or would you prefer to pass them to someone else?

**Comment by msleckman** [comment]
@jds485 I can handle this issue

**Comment by jds485** [comment]
Should check how the 2000 (FORE-SCE) and 2001 (NLCD) data compare across all reaches. See #134 for different in reach 287_1.

**Comment by msleckman** [comment]
ok PR #135 should check this through update following #134 merge.

**Comment by jds485** [comment]
Some catchments have NAs in a large portion of the area. Should check where these are and if we should fill in values for NA
![image](https://user-images.githubusercontent.com/8761242/162473065-51349642-fc99-426d-859a-b95397ef5dac.png)

**Comment by msleckman** [comment]
Determined that these catchments have a large portion of NA because they are over open ocean which doesnt have a lc class. 
![image](https://user-images.githubusercontent.com/36547359/162540020-e0af5f5a-d093-431d-8b29-2400fc82e4db.png)
