### ISSUE TITLE
Update pipeline data processing with edited catchments

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#111]
After #110, our pipeline now has HRUs for all PRMS segments. These HRUs are in the `p1_catchments_edited_sf` target.

I think we can replace targets `p1_catchments_sf` and `p1_catchments_sf_valid` with `p1_catchments_edited_sf`.

**Comment by jds485** [comment]
@msleckman : would you be able to do this? I think it mostly affects the targets you've closely worked on (land cover, road salt)

**Comment by msleckman** [comment]
yes I can. Target `p1_catchments_edited` will replace `p1_catchments_sf_valid` in the pipeline.
