### ISSUE TITLE
Reassess sites-to-segs search radius 

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#112]
In USGS-R/drb-do-ml#36, we realized that the search radius being used to match sites to segments likely resulted in many headwater streams being matched to the mainstem rivers represented in the PRMS network. This issue includes the following steps:

- [x] Look at a few specific conductance sites to assess whether this issue also applies to our SC sites
- [x] If the search radius should be adjusted, incorporate the code changes in USGS-R/drb-do-ml#67

**Comment by jds485** [comment]
Thanks for discovering this issue! I'm supportive of reducing the search radius to 1 km (or shorter) and dropping sites that are further away than that. It would be helpful to know how many sites, particularly continuous, are dropped to potentially encourage modeling at finer NHD scale in the future.

**Comment by lekoenig** [comment]
We're currently snapping points to segments by searching for the nearest segment within a radius of 0.1 degrees (~10 km). The plot below shows the distance between our SC sites (including discrete + NWIS observations) and the matched segment, showing that there are quite a few sites that are matched to reaches that are relatively far away (i.e., ~1360 sites out of 3449 total sites are > 1 km away from their matched segment). 

![snapped_dist](https://user-images.githubusercontent.com/8785034/159008636-550e5750-aba3-4489-bd5c-f12939e1a9d0.png)

Most of these sites that don't get matched/are matched at long distances are discrete sites. However, there are some NWIS sites that are getting snapped to PRMS segments even though the sites probably aren't located on those segments. NWIS [01478950](https://waterdata.usgs.gov/monitoring-location/01478950/#parameterCode=00065&period=P7D) (on Pike Creek and _not_ the Christina River, which is shown in red) is an example of that:

![snap_ex](https://user-images.githubusercontent.com/8785034/159016439-cd16e43f-ccb5-4df6-a321-09fc5c88c57a.png)

**Comment by lekoenig** [comment]
So I'd suggest we should reduce our search radius. In other projects such as temperature and now DO, we use a search radius of 500 m (e.g. see [lines](https://github.com/USGS-R/2wp-temp-observations/blob/174875b69c335436bf5acdeee8a53e5334ac72de/6_network.yml) 56-61 in the 2wp-temp repo). If we reduce our search radius to 500 m, we lose 26 NWIS gages out of 125. I quickly checked the location of these 26 gages and most of them are located on streams not represented by the PRMS network. But there are also edge cases where larger rivers might not get snapped if they're wider than 500 m (e.g. issue https://github.com/USGS-R/delaware-model-prep/issues/34 in delaware-model-prep). I noticed this with sites on the Delaware River (e.g. 01474703 and 01477050, which are ~620 and 630 m away from that segment, respectively. 

I'm leaning towards keeping the search radius at 500 m, but adding special handling to retain 01474703 and 01477050. Implementing this change would result in a loss of 24 NWIS gages and 9,048 NWIS observation-days (~5% of our total NWIS obs-days for SC).

**Comment by jds485** [comment]
Thanks for the update. Using 500 m and special handling for points where the river width is large sounds good to me. River width is an attribute that could be used to determine which segments should receive special handling. `seg_width` in `p1_sntemp_inputs_outputs`. The maximum width is 125.7 m, so this attribute must be measuring something other than river width...the metadata says river width in m, though.

**Comment by jds485** [comment]
I used Google Earth for a quick river width estimation. It seems like the main stem south of Trenton is > 500 m. It doesn't look like any of the tributaries are > 500 m. I can quickly grab all of the main stem segment numbers that could use > 500 m tolerance, but would not have a quick way to say what the tolerance should be for these reaches

**Comment by lekoenig** [comment]
Thanks for looking into this (I haven't looked at `p1_sntemp_inputs_outputs` closely, but that's odd that 125.7 m is the largest width). The other large river sites seem to be retained OK using a 500 m search radius, so that's why I assigned those two NWIS sites on the Delaware. We could retain segs instead of sites (i.e., all sites that match to a seg downstream of Trenton), but I'd have to do a quick check that we don't re-introduce any tributaries that way.

**Comment by jds485** [comment]
I don't think it would introduce tributaries using the recursive function to grab all PRMS segments downstream of 333_1. Or do you mean that the samples could be on tributaries and not the main stem?

**Comment by lekoenig** [comment]
> I don't think it would introduce tributaries using the a recursive function to grab all PRMS segments downstream of 333_1. Or do you mean that the samples could be on tributaries and not the main stem?

Yeah, thanks for clarifying. I meant tributary samples that got matched to the mainstem. I don't expect that to be an issue if we're sticking with a 500 m radius, though.
