### ISSUE TITLE
After S3 Database is Accessible: Move Inputs to S3 and Create target to pull from S3

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#12]
When S3 storage becomes available, we'll switch to hosting the data there instead of on GitHub. We'll need a target(s) to stream the data from S3.

Using this as a place to track which inputs we need to move to S3.

Variables:
1_fetch/In/DRB.WQdata.rds

**Comment by lekoenig** [comment]
Will we actually want to move DRB.WQdata.rds to S3 or simply change that target to fetch the data from ScienceBase? We had initially included the binary .rds file in 1_fetch/in to avoid problems with ScienceBase going down, however, we'll be bringing in other input datasets from ScienceBase as our data prep pipeline grows. Do we expect to copy each of those to S3? Or do we envision using S3 primarily as storage for processed data that represent modeling inputs? I'm a bit wary of creating multiple copies of ScienceBase data products but then again, I know it's a hassle when ScienceBase goes down..

**Comment by jds485** [comment]
Maybe we can use both ScienceBase and S3 using a `tryCatch` framework. First try ScienceBase, then use the S3 data that we upload if ScienceBase is down.

**Comment by jds485** [comment]
> do we envision using S3 primarily as storage for processed data that represent modeling inputs?

I would prefer to use S3 for modeling inputs and outputs. Those are the data we'll eventually need to generate a ScienceBase release

**Comment by lekoenig** [comment]
> I would prefer to use S3 for modeling inputs and outputs. Those are the data we'll eventually need to generate a ScienceBase release

I agree that we should use S3 for storing modeling inputs/outputs. My question was more about whether we'll also store copies of upstream binary files containing raw or pre-processed data there. If SB lapses become a barrier and we do opt to store pre-processed data on S3, I like your `tryCatch` idea.

**Comment by lekoenig** [comment]
Based on our discussion on 11/24/2021, let's hold off on writing any pre-processed data files to S3 to avoid multiple copies of data files and reduce S3 read/write charges. Hopefully disruptions caused by ScienceBase outages will be minimal if we don't need to re-build those targets very often but we can revisit if it becomes a problem. 

I'm leaving this issue open since we still need to add functionality to write to S3 within our pipelines framework.

**Comment by jds485** [comment]
I think this issue is now outdated with our recent S3 discussion. Good to close and keep #84 instead?

**Comment by lekoenig** [comment]
Yep, let's close! Issue #84 now captures the steps we intend to take to interface S3 with our targets pipeline.
