### ISSUE TITLE
Need special handling for PRMS segid 3_1, 8_1,51_1, and 2124_1 in `p2_FORESCE_LC_per_catchment_reclass_tot`

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#126]
Please see PR #123 draft for details on changes to main 

No TOT Land Cover proportions calculated for 4 PRMS segid - `3_1`, `8_1`, `51_1`, and `2124_1`. 
As such, target `p2_FORESCE_LC_per_catchment_reclass_tot` - which calculates all land cover proportions for the total upstream area for each PRMS_segid - has nrow = `445` (not the expected `459`).

**Case 1:**
`3_1`, `8_1`, `51_1` are not in the source dataset `p1_prms_reach_attr` that maps the upstream and downstream segments for every given segment, and allows us to recursively determine the all segments upstream of given segment. `p1_prms_reach_attr` just has `3_2`, `8_2`, and `51_2`. 

TOT prop values are therefore calculated for `3_2`, `8_2`, and `51_2`. How should we assign proportions to `3_1`, `8_1`, and `51_1`. 

- [x] Decide how to assign proportions to these 3 PRMS_segid
	
**Case 2:**
To produce the TOT FORESCE proportions target `p2_FORESCE_LC_per_catchment_reclass_tot` ,`hru_segment` values are used to merge  the “recursed” reach attributes dataset (`p2_prms_attribute_df`) with the foresce CAT LC proportions target, `p2_FORESCE_LC_per_catchment_reclass_cat`, which ultimately outputs `p2_FORESCE_LC_per_catchment_reclass_tot`. 
Typically, the `$hru_segment` == `$PRMS_segid` without the suffix `_*` 

However, the hru_segment for PRMS_segid:2124_1 is 2131 (not 2124 as expected). 

```
> p2_FORESCE_LC_per_catchment_reclass_cat[[1]][p2_FORESCE_LC_per_catchment_reclass_cat[[1]]$PRMS_segid == '2124_1',]
# A tibble: 1 × 14
# Groups:   PRMS_segid [1]
  PRMS_segid hru_segment total_PRMS_area prop_lcClass_3 prop_lcClass_2 prop_lcClass_1 prop_lcClass_4 prop_lcClass_7 prop_lcClass_8
  <chr>      <chr>                 <dbl>          <dbl>          <dbl>          <dbl>          <dbl>          <dbl>          <dbl>
1 2124_1     2131              38784764.          0.405         0.0347         0.0293         0.0598          0.120        0.00207
# … with 5 more variables: prop_lcClass_9 <dbl>, prop_lcClass_10 <dbl>, prop_lcClass_6 <dbl>, prop_lcClass_5 <dbl>, Year <chr>
``` 

- [x] Determine why this is occurring to PRMS_segid:2124_1 and map out how to handle this case

**For both cases:** 
- [x] Add special handling for both cases when creating the `p2_FORESCE_LC_per_catchment_reclass_tot` 
- [ ] Suggest producing a separate function for this process that will replace the lengthy code blocks that produce `p2_prms_attribute_df` and `p2_FORESCE_LC_per_catchment_reclass_tot`

**Comment by jds485** [comment]
I have an idea for handling Case 1, but it depends on the TOT area being correct for _1 and _2 segments (see #122). 

TOT_1 = (TOT_2 * TOT_AREA_2 - CAT_2 * CAT_AREA_2)/(TOT_AREA_2 - CAT_AREA_2)

where TOT_AREA_2 - CAT_AREA_2 should equal TOT_AREA_1 + very small error

**Comment by jds485** [comment]
The equation I posted will not work as written for these segments because there are additional reaches upstream of _2 vs. _1 segments. Example for 3_1, 3_2, 8_1, and 8_2:

![image](https://user-images.githubusercontent.com/8761242/159565292-1f7e4cd1-e514-42ff-830e-fd14b25d3945.png)

**Comment by msleckman** [comment]
> The equation I posted will not work as written for these segments because there are additional reaches upstream of _2 vs. _1 segments. Example for 3_1, 3_2, 8_1, and 8_2:

If `_1` is always upstream of `_2`, then can we assume the TOT that is attributed to `_2` includes `_1`  ?

**Comment by jds485** [comment]
Yes, _1 is always upstream of _2. The issue is that there are tributaries upstream of _2 that are not upstream of _1 (black segment in between the red and blue segments in the figure).

**Comment by lekoenig** [comment]
Thinking about **case 1**, I don't really have a clever solution here because of the reasons that Jared's already mentioned. I would recommend adding special handling within the `p2_prms_attribute_df` target as opposed to other downstream targets like the FORESCE ones. Two options stick out to me: 

- the first being to edit `p2_prms_attribute_df` to use the xwalk table and use NHD (example [here](https://github.com/USGS-R/drb-inland-salinity-ml/issues/101#issuecomment-1058508325)). 
- brute force edit `p1_prms_reach_attr` to include the split segments with a "_2" suffix. 

If you're hoping to edit what you already have using the recursive function that you and Jared came up with, I wonder if the code below to carry out the brute force method would work? I haven't spent much time with the target `p2_prms_attribute_df` so I'm not as familiar with the expected output and would appreciate checks by you or Jared.

```
munge_reach_attr_table <- function(attr_tbl){
  
  # Special handling to add split segments with _2 suffix to prms
  # reach attribute table; values for from_segs and to_seg were
  # derived based on visual inspection and manually entered
  attr_tbl_w_splitsegs <- attr_tbl %>%
    mutate(to_seg = as.character(to_seg)) %>%
    tibble::add_row(subseg_id = "3_1", from_segs = "1", subseg_seg = 3, to_seg = "3_2", seg_id_nat = 1437) %>%
    tibble::add_row(subseg_id = "8_1", from_segs = "", subseg_seg = 8, to_seg = "8_2", seg_id_nat = 1442) %>%
    tibble::add_row(subseg_id = "51_1", from_segs = "43", subseg_seg = 51, to_seg = "51_2", seg_id_nat = 1485) %>%
    # now adjust the split segments with _1 suffix
    mutate(
      from_segs = case_when(
        subseg_id == "3_2" ~ "3_1;8",
        subseg_id == "8_2" ~ "8_1;2",
        subseg_id == "51_2" ~ "51_1;50"),
      to_seg = case_when(
        subseg_id == "3_2" ~ "4",
        subseg_id == "8_2" ~ "3",
        subseg_id == "51_2" ~ "52")
      )
  
  # Find all segments upstream of a given PRMS segment
  attr_tbl_out <- attr_tbl_w_splitsegs %>%
    select(subseg_id,subseg_seg,from_segs,to_seg) %>% 
    # Update `from_segs` col by splitting the individual segs in a list (can then loop through the list) 
    mutate(from_segs = stringr::str_split(string = from_segs, pattern = ';', simplify = F)) %>% 
    rowwise() %>%
    # Collect all upstream segs per individual seg_id using recursive_fun() (row wise application)
    mutate(all_from_segs = list(recursive_fun(x = subseg_seg,  df = ., col1 = 'subseg_seg', col2 = 'from_segs'))) %>%
    # unest to have new rows for each upstream catchment
    unnest(all_from_segs, keep_empty = TRUE) %>%
    # change col type to be able to compute
    dplyr::mutate(all_from_segs = as.integer(all_from_segs))
  
  return(attr_tbl_out)
      
}
```

**Comment by jds485** [comment]
Here is a plot for 2124_1. It seems correct that the `hru_segment = 2131` for segment 2124_1 because the segment is entirely within this HRU. For now, I'll add manual handling for segment 2124_1 for this problem. @lekoenig: should the `hru_segment` for 2124_1 be edited in the GFv1_catchments_edited gpkg file?
![image](https://user-images.githubusercontent.com/8761242/161285717-56c726b3-cf13-467f-a92d-069cde8339c2.png)
