### ISSUE TITLE
Compute TOT FORESCE from CAT data

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#138]
Use the update reach network table to update the computed TOT FORESCE land cover data

**Comment by msleckman** [comment]
Notes
* Target `p2_FORESCE_LC_per_catchment_reclass_tot` is outputed in the main pipeline but is incorrect is incorrect at the moment and this issue should address this. 
* Downstream target `p2_all_lulc_data_tot` (from PR #135) will change based on changes from this issue.

**Comment by jds485** [comment]
Just confirming that `p2_FORESCE_LC_per_catchment_reclass_tot` is incorrect because we edited the land cover reclassification table to assign value 0 (no data) to NA instead of to corn. That causes the sum of proportions for `p2_FORESCE_LC_per_catchment_reclass_cat` to be less than 1 for a catchment whenever there are NAs in the catchment. So, I think this issue is addressing getting the CAT proportions to sum to 1 for each catchment because that will fix the TOT values. Is that right?

**Comment by jds485** [comment]
The NA values only appear in the estuary and on the exterior of the grid (red in map). I'm planning to address this problem by equally adjusting the proportions of non-NA land cover values to make up for the NA proportion. This makes me wonder if we should update the area of HRUs to be "land area" instead of "polygon area" or "total area" that includes a large water proportion for the estuary.
![image](https://user-images.githubusercontent.com/8761242/163215789-629f543d-be69-47e7-b056-6b350e61eac6.png)
