### ISSUE TITLE
Logistics of integrating gridmet into pipeline

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-inland-salinity-ml#150]
The gridmet data has been aggregated to the DRB HRU's and is on Caldera, `/caldera/projects/usgs/water/impd/pump/gridmet/drb_gridmet_tools/data/out/drb_climate_2022_04_06.nc`,  but a straightforward way of integrating into our pipeline is not coming to me. It's a large-ish file (842 MB).

**Not possible options:**
- host it on GH; it's too big

**Possible options:**
- we just use the file on Caldera via Tallgrass or Denali. I hesitate to be totally dependent on HPC, though b/c sometimes you can't get a node 
- we somehow download it from Caldera onto our local machines. We could maybe do this using `scp`, but that's difficult to program because we'd all have to log on to Tallgrass/Denali with our own credentials
- we rebuild each time. This could work. It takes ~10 minutes to build, so not terrible. 

There are probably other options that I'm not thinking of ...

**Comment by jds485** [comment]
4th option: We discussed yesterday placing the gridMET data on S3
