### ISSUE TITLE
error when building ind targets with S3

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-inland-salinity-ml#153]
I ran into another error when using "aws" as the `repostitory`. When building these three targets: `p3_daily_timeseries_ind_csv, p3_inst_timeseries_ind_csv, p3_wqp_ind_csv`.

![image](https://user-images.githubusercontent.com/6943441/167707987-cda159bc-0b25-4c58-ab7f-af8545e3c3f1.png)

For each of these targets, the `save_target_ind_files` function from `3_visualize/src/summarize_timeseries.R` is called. In this function it calls the "path" column from the `tar_meta` for the given target and tries to do an `unlist` on it:
https://github.com/USGS-R/drb-inland-salinity-ml/blob/d1e55ddab51387c88b338302de2b0d6b47734292/3_visualize/src/summarize_timeseries.R#L11-L13

When using S3 the `tar_meta` is different than when using the local storage:

"local" `tar_meta`:
![image](https://user-images.githubusercontent.com/6943441/167708631-d799bea2-b171-47c7-aae1-7e128747d251.png)

"aws" `tar_meta`:
![image](https://user-images.githubusercontent.com/6943441/167708100-44855a97-9d03-4e47-91e8-b29f889b8cfb.png)

---
## Proposed workaround
Make the targets that we are making indicator files for `p3_daily_timeseries_png, p3_hourly_timeseries_png, p2_wqp_SC_data` local. (similar to #152)

**Comment by jds485** [comment]
I think local is okay for these ind files if the data are tracked in S3. Changes in the data will propagate to the ind files.
