### ISSUE TITLE
Create a variable to toggle repository from 'aws' to 'local'

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#172]
For testing or troubleshooting code, it'd be nice to be able to readily toggle all of the targets that currently use `repository = 'aws'` by default to `'local'` instead. Perhaps something similar to `NWIS_cue`?

**Comment by jds485** [comment]
I think we can already do this. The default repository is set globally within `tar_option_set`:

```
tar_option_set(packages = c("tidyverse", "lubridate",
                            "rmarkdown","dataRetrieval",
                            "knitr","leaflet","sf",
                            "purrr", "sbtools", "terra",
                            "patchwork", "glue",'nhdplusTools'),
               resources = tar_resources(
                 aws = tar_resources_aws(bucket = "drb-inland-salinity")),
               repository = "aws",
               format = "rds",
               priority = 0.8
               )
```


Changing repository here to "local" will work. I'll note that this method can only be used for testing. It will cause all targets to rebuild (maybe good if for troubleshooting), and change the meta file. 

To troubleshoot particular targets, it probably is simpler to add "repository = 'local'" within their `tar_target()` call
