### ISSUE TITLE
Error building pipeline with `repository = "local"`

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#177]
In the README, the instructions indicate that the pipeline can be built locally by toggling the `repository` option in `_targets.R` from `"aws"` to `"local"`. I'm recording some behavior I observed when trying this out for a PR review:

```r
* start target p1_nwis_sites_inst_multipleTS_csv
x error target p1_nwis_sites_inst_multipleTS_csv
* end pipeline: 4.726 minutes
Error : could not load dependencies of target p1_nwis_sites_inst_multipleTS_csv. invalid 'description' argument
```

I think this occurs because we've committed the tar_meta file and set `NWIS_cue = "never"`. Certain targets, in this case `p1_nwis_sites` don't get rebuilt using the `"local"` setting but then downstream targets can't find these dependencies.

See below, where `p1_nwis_sites` still has `repository = "aws"` even though `repository = "local"`:
```r
> tar_meta() %>% filter(grepl("multipleTS", name))
# A tibble: 2 x 18
  name         type  data  command depend    seed path  time                size       bytes format repository iteration parent children seconds warnings error
  <chr>        <chr> <chr> <chr>   <chr>    <int> <lis> <dttm>              <chr>      <dbl> <chr>  <chr>      <chr>     <chr>  <list>     <dbl> <lgl>    <chr>
1 find_sites_~ func~ a90a~ NA      NA     NA      <chr> NA                  NA    NA         NA     NA         NA        NA     <chr>         NA NA       NA   
2 p1_nwis_sit~ stem  48e8~ 7783ff~ f821b~ -1.52e9 <chr> 2022-06-16 15:09:58 NA     1.11e-308 file   aws        vector    NA     <chr>          0 NA       coul~
>
```

**Comment by jds485** [comment]
Thanks for documenting this. One way around this could be to specify `repository = aws` within the `tar_target` calls for all targets with `cue = never`. That way setting the global option of `repository = local` would only affect the other targets.

**Comment by jds485** [comment]
Adding some other thoughts we may want to test out and/or add to the README:

- Adding `AWS_SHARED_CREDENTIALS_FILE = "path/to/credentials"` to `Sys.setenv` was needed for `tar_outdated()` to detect that all targets were built and available on S3. Was that coincidental? Or is that necessary?

- If an error is thrown when fetching a target, that may(will?) cause the meta file to have an error in it for that target and the target may(will?) be rebuilt the next time `tar_make()` is run. If you do not want that target to rebuild and instead want to try fetching it again, you can `git stash` to reset the targets meta file, and then `tar_make()`.

**Comment by jds485** [comment]
Following up on a comment in #175 by @lekoenig [here](https://github.com/USGS-R/drb-inland-salinity-ml/pull/175#pullrequestreview-1057928577):
- what happened when you used `through`? I found the targets documentation unclear for that method. Did it rebuild the targets?

**Comment by lekoenig** [comment]
> what happened when you used cue = through? I found the targets documentation unclear for that method. Did it rebuild the targets?

Yes, it rebuilt those NWIS targets.

**Comment by jds485** [comment]
Okay, thanks. I'm going to try making the edit to add `repository = aws` within the `tar_target` calls for all targets with `cue = never`, and then see if using the global option of `repository = local` works to pull the `cue = never` targets from S3

**Comment by jds485** [comment]
> Adding AWS_SHARED_CREDENTIALS_FILE = "path/to/credentials" to Sys.setenv was needed for tar_outdated() to detect that all targets were built and available on S3. Was that coincidental? Or is that necessary?

I think this was coincidental. I did not have this problem when checking the pipeline for #179
