### ISSUE TITLE
Match SC locations to PRMS segments

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#18]
We need to match point observations to PRMS segments. Jeff and Alison think that David Watkins has developed an algorithm for doing the spatial join, so we should check on GitLab.

**Comment by jsadler2** [comment]
I can look into this.

**Comment by lekoenig** [comment]
Thanks, Jeff! I'll create a list of unique lat/lon that represent our specific conductance point locations. I expect the site list to look like our DO site list (https://github.com/USGS-R/drb-do-ml/issues/19#issue-1055508196), so just let me know if there is additional information we'll need.
