### ISSUE TITLE
Add function to plot empirical CDFs of model performance

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#189]
function should accept a list of model results as input and make one curve per model.

Model results columns 
residuals
PRMS_segid
Date

Example targets with model predictions:
`p4_pred_RF_static_dynamic_temporal_test`
`p4_pred_RF_min_static_dynamic_temporal_test`
`p4_pred_RF_dynamic_temporal_test`
These are lists. The `$preds` list is a data frame with errsq (squared residual error for each day), PRMS_segid, Month, and Year (and some other columns).

Could have options to make:
a CDF plot for each reach
one CDF over all reaches
a CDF for selected months/years (facet wrapped?)

Example: summary RMSE by reach:
summarize(group_by(p4_pred_RF_static_dynamic_temporal$pred, PRMS_segid), 
                                 RMSE = sqrt(mean(errsq)),
                                 RMSE_log10 = log10(RMSE))

Axes: 
empircal CDF quantiles
error metric values for those quantiles (e.g., RMSE)

**Comment by jds485** [comment]
@lekoenig: I think this would be most helpful to have for AGU

**Comment by lekoenig** [comment]
Thanks for providing all of these ideas, @jds485! Here are some plots from a function that can either plot:

1) one CDF over all reaches:
![test](https://user-images.githubusercontent.com/8785034/205694905-f2464499-7776-41fe-a00a-7ef5813f1b7a.png)


2) a CDF plot showing the CDF of RMSE's for each date for any selected reach(es):
![test2](https://user-images.githubusercontent.com/8785034/205694939-f9af096a-143e-414e-8bba-963156a69fe8.png)


3) a plot that shows the CDF over all reaches, but only for selected months and years:
![test3](https://user-images.githubusercontent.com/8785034/205694961-ecb615eb-9aae-49bc-87fb-80261f6daf29.png)

The user can choose whether to show a logged x axis or not. We can edit or parameterize any of the plot formatting, but let me know if these plots are what we're looking for and I can open a new PR that addresses this issue.

**Comment by jds485** [comment]
Thanks! These look good to me. Do you have an option to plot results for several models (one CDF per model)?

**Comment by lekoenig** [comment]
> Do you have an option to plot results for several models (one CDF per model)?

By several models, do you mean if say, we wanted to combine models `p4_pred_RF_static_dynamic_temporal_test` and `p4_pred_RF_min_static_dynamic_temporal_test` and display on the same set of plots? Right now, the function works on one set of model results but I could play around with adding that functionality.

**Comment by jds485** [comment]
I was thinking about supplying the model results as a list, and then the function would plot 1 CDF per list element (model)

**Comment by lekoenig** [comment]
> I was thinking about supplying the model results as a list, and then the function would plot 1 CDF per list element (model)

Can you give an example of the list you're envisioning? `p4_pred_RF_static_dynamic_temporal_test` is a list (containing data frames `target`, `pred`, and `metrics`). Would this input be a list of lists, where, for example, we'd pull the `pred` data frame from each list, and plot 1 CDF per model (1 CDF per `pred` data frame)?

**Comment by jds485** [comment]
> Would this input be a list of lists...

yes, that's what I'm envisioning
