### ISSUE TITLE
Parallel zarr file writing

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#198]
`p2_all_attr_zarr` takes about 20 minutes to write zarr files. It would be nice to parallelize the writing over the columns. Amelia is looking into this.

**Comment by jds485** [comment]
Turns out this is largely a result of time to download the `p2_all_attr` rds file from S3. Closing this issue.

**Comment by lekoenig** [comment]
> Turns out this is largely a result of time to download the p2_all_attr rds file from S3.

Ah, bummer, thanks for looking into it. I can attest that downloading `p2_all_attr` from S3 was taking a pretty long time for me yesterday (after 20 minutes, I gave up and just tested the obs zarr target). So this makes sense.
