### ISSUE TITLE
NWIS sites added (and maybe removed?) over time

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#29]
While rebuilding targets for PR review #27, I learned that NWIS sites can be added (and maybe also removed?) from one day to the next, which raises reproducibility concerns. We will need a way to handle tracking exactly which sites are pulled to ensure consistency among repo developers and future users.

To elaborate, the new site had data for most of the specified date range. So it should have been gathered if it were previously available on NWIS.

**Comment by jds485** [comment]
If we git track a file with sites, it could have columns for: 
site name, and
total number of samples, which could be split into 3 columns: instantaneous, WQP, and daily

**Comment by lekoenig** [comment]
Adding a comment here that we've added a `sitelist_summary` target to track any changes in the number of daily/instantaneous NWIS sites over time. We did come to the conclusion that for site [01482537](https://waterdata.usgs.gov/nj/nwis/inventory/?site_no=01482537), which initiated this issue, there were recent changes made by the local WSC that made these older data publicly accessible through the API (and thus, gathered within our pipeline). More details in this [Teams conversation](https://teams.microsoft.com/l/message/19:264c78fefa624bcfaf46ac10b9305f5e@thread.skype/1639492810490?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&groupId=2651eb2e-8cf1-4caa-a084-0a11facc1d36&parentMessageId=1639492810490&teamName=GS-WMA%20IIDD%20Staff&channelName=Function%20-%20Data%20Pipelines&createdTime=1639492810490).
