### ISSUE TITLE
Clarify "Conductivity" assignment with Meg Shoda

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#3]
Other thoughts:
Some of the `CharacteristicName` values are `Conductivity` even though the `param` is `Specific Conductivity`. It might be safest to drop the few Conductivity values for now because they might not be temperature corrected. 

Does `specific conductance, lab` indicate that the temperature correction was applied in the lab instead of when sampled? Does it matter where the correction was applied to get the correct specific conductance value?

_Originally posted by @jds485 in https://github.com/USGS-R/drb-inland-salinity-ml/discussions/2#discussioncomment-1539812_

**Comment by lekoenig** [comment]
The "preliminary" tag is from WQP, but was retained throughout the harmonized dataset. I expected the preliminary data to be heavily skewed towards recent years and while that's true to some extent, there's a decent number of pre-2015 samples out there, too (see below). This is strange to me for a field parameter like specific conductance since there's no lag time to analyze the sample in a lab, backlog of QC checks, etc. I'm guessing users just don't get around to updating the status. The harmonized product incorporates some flags for extreme values which is why I've left in the preliminary samples for now (as in option 2 above). 

I've also created an issue (#6) to check back on ~2017+ samples labeled "preliminary" and see how much those differ from approved data.

![spc_data_prelim](https://user-images.githubusercontent.com/8785034/139481374-afe26cbe-7a0e-481a-9c7f-956aad784522.png)

**Comment by jds485** [comment]
Wow, that is a surprising distribution! 

> The harmonized product incorporates some flags for extreme values which is why I've left in the preliminary samples for now

Is "preliminary" used used when samples are extreme?

**Comment by lekoenig** [comment]
> Is "preliminary" used used when samples are extreme?

No, not necessarily. ResultStatusIdentifier (e.g. "Accepted", "Preliminary", etc.) is a column entered by the original user. This variable is used in the harmonization process to decide which samples to keep IF there are apparent duplicates, but otherwise the decision steps to retain a sample - including for extreme or implausible values/units - don't appear to consider the original ResultStatusIdentifier.

**Comment by lekoenig** [comment]
> Some of the CharacteristicName values are Conductivity even though the param is Specific Conductivity. It might be safest to drop the few Conductivity values for now because they might not be temperature corrected.

According to Dave Dupre, "conductivity" and "specific conductance" represent "two different substances in the USGS SRS due to the temperature-normalized basis", so my preference would be to not combine them. Meg Shoda doesn't recall explicit conversations related to the ~60 data points tagged as "Conductivity" within the harmonized dataset (these samples all come from other agency data in the WQP). Because these samples represent such a small proportion of the SC data and because "Conductivity" does not match any USGS-defined parameters, we will continue to omit them from the filtered SC data.

**Comment by jds485** [comment]
Is this issue resolved?

**Comment by lekoenig** [comment]
Yes, this issue can be considered resolved and closed. I received feedback from Meg Shoda and others about:

1. whether samples tagged with `CharacteristicName == "Conductivity"` should be retained. _We have decided that no, they should not be included in our WQP data (see comments above)._
2. spatial datum associated with lat/lon in harmonized WQP data. _Spatial datum was not retained as a column within the harmonized dataset, so I have fetched the datum for each site ID in our filtered dataset from the full WQP (see `2_process/src/create_site_list.R`)_
3. Consideration of data tagged in WQP as "preliminary." _The harmonized dataset does not omit samples simply because they were tagged as "preliminary" (see comments above)._ I had been keeping this issue open as a reminder to reassess whether we want to retain preliminary data (for data from WQP as well as NWIS), but at this point that topic is redundant with issue #6.
