### ISSUE TITLE
Process Bock road salt raster to PRMS reaches

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#32]

**Comment by lekoenig** [comment]
Was this issue resolved in PR #44? If so, can it be closed? 

I know we have separate issues/PR for processing the road salt raster stack (issue #74 and PR #76), so I'm wondering if this issue is still active. @msleckman

**Comment by msleckman** [comment]
Yea duplicate of #74 and resolved and addressed in PR #44. 

Closing.
