### ISSUE TITLE
Evaluate SC signal downstream of reservoirs 

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#40]
- Identify sites downstream of reservoirs 
- Evaluate SC signal for reservoir-impacted sites to determine whether distance to reservoir would be a useful attribute to add

**Comment by lekoenig** [comment]
I used the network attributes table from the temperature project (`p1_prms_reach_attr`) to look for any SC sites associated with the following reach classes:

- the snapped PRMS segment is 1 or 2 segments downstream of a reservoir
- the snapped segment ending point is within a reservoir or downstream of a reservoir
- a reservoir is fully contained within the snapped segment

There are 54 segments with these classifications in the DRB, representing 11 instantaneous SC sites. I inspected those 11 sites and found that 6 of them should be considered further for assessing reservoir influence. For the others, the site either appeared to be located upstream of the reservoir along the snapped segment, or the site didn't appear to intersect the PRMS network. 

![waffle](https://user-images.githubusercontent.com/8785034/153635335-6393f1ad-2681-4b2e-b0c4-de142acf99f6.png)


To evaluate whether the SC signal is affected by an upstream reservoir, I took two main approaches to 1) compare the median and range of SC observations, and 2) compare the relative variation of SC with discharge between the reservoir group and all other sites. 

**SC central tendency and spread**

I generally expected that if upstream reservoirs influenced SC, those sites would potentially have lower max/median SC because SC might be more influenced by reservoir (and precipitation) dynamics as opposed to groundwater inputs of ions contributing to TDS. Road salt obviously complicates that, but these sites are located in the upper portion of the watershed where (I think) there is less impervious cover that would require deicing.  With such a small number of sites I haven't done any formal statistical evaluation of the reservoir sites vs. non-reservoir sites. For visualization, I split the reservoir sites into those that were located below a reservoir (i.e. the reservoir falls on that site's PRMS segment; n=3) and those that were downstream of a reservoir, but the reservoir is some distance upstream (1 or 2 PRMS segments away; n=3). 

![summary_boxplots](https://user-images.githubusercontent.com/8785034/153630626-5ad2ead3-cb4d-4344-bd43-6b91b5402c01.png)

The reservoir sites overlap the distribution for the full population of sites, but it does look like the sites located below reservoirs may have relatively lower salinity or a smaller range in SC relative to the average site in the DRB. 

**SC variability and concentration-discharge**

For each instantaneous SC site, I downloaded the discharge data (where available) to look at how SC varies with changes in discharge. I generally expected that for reservoir-influenced sites, SC would be relatively invariant with changes in discharge, unlike the flushing and/or dilution responses we often see due to limitation by solute transport or supply. This too is probably more complicated but I started there. 

In terms of the C-Q relationships, the general trend in the DRB is a negative relationship between SC and discharge, at least over longer time-scales. Looking at the C-Q slopes, the reservoir-sites again overlap the distribution for the full population of sites, but it does appear that they fall along the right-hand side of the distribution towards less negative slopes:
![CQ_compare](https://user-images.githubusercontent.com/8785034/153635801-402673e1-c215-4cf3-acd5-7a5c84244367.png)

As an example, here's the C-Q plot for site 01433500, which is located below a reservoir:

![01433500_cq_plot](https://user-images.githubusercontent.com/8785034/153636633-a1f1a907-03ca-4f6e-a045-df2b20680b84.png)

I also compared the relative coefficients of variation (CV-sc: CV-q) to look at SC variability relative to streamflow. CV-sc: CV-q was generally much lower than 1, indicating that SC is less variable than Q. Nothing jumps out at me in terms of reservoir sites versus all other sites:

![CVCQ_compare](https://user-images.githubusercontent.com/8785034/153638388-a696bd3b-2f8c-4519-a641-2f1da9613c09.png)

Overall, it's hard to draw strong conclusions from such a small number of reservoir-influenced sites. However, based on this exploratory analysis I think we could make the case that reservoir distance (or some proxy) could be useful in the static model. Creating a binary variable based on the information in `p1_prms_reach_attr` would be a very do-able place to start. Calculating fish distances between sites and nearest upstream reservoir is possible, but would represent a substantially bigger time investment. 

I'm open to and interested in any other comments/interpretations, or ideas for how to quickly explore the possible influence of reservoirs on river conductance.

**Comment by jds485** [comment]
Thanks for doing this analysis! 

> it does look like the sites located below reservoirs may have relatively lower salinity or a smaller range in SC relative to the average site in the DRB

This could also result from other factors you mentioned, like these 6 sites being less developed compared to the others. Based on these results and for the sake of time, I'm comfortable omitting a reservoir variable for now. I'll check model residuals for these sites vs. others to see if there are any patterns we think can be attributed to the reservoirs. 

It could be that the reservoir release signals appear further downstream in the network where this water dilutes more saline water that originates in more developed areas. For example, in drier conditions, we know there is some signal once the released water hits the estuary.

**Comment by lekoenig** [comment]
Thanks, that sounds like a good plan to me!
