### ISSUE TITLE
Gather NADP data for DRB

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#42]
We're interested in atmospheric deposition of Na and Cl in the DRB. There should be multiple years available, so tasks might include:

- Assess interannual variability of Cl and Na deposition rates in DRB
- If little interannual variability, decide whether to pull most recent NADP values, for example, or to average all years to come up with average deposition rates for Cl and Na
- Become more familiar with the format of these data - are the data published as rasters (maps)? More information here: https://nadp.slh.wisc.edu/committees/tdep/

**Comment by jds485** [comment]
I looked at these data and they are available as images and grids. I'm not sure if the images are spatially referenced, but the grids are. Hopefully the in-development raster to reach script can be used for this dataset, too. I viewed several years for dry and wet deposition of Na and Cl and the patterns looked similar from year to year. Wet deposition was a little more spatially variable, I'd assume due to precipitation patterns. My analysis was not exhaustive, though

**Comment by jds485** [comment]
Just noting that these have been processed to NHD reaches for Cl, Mg, and Ca. Starting there could be simpler than having to start from the raw rasters. And someone (Mike?, Andrew?) must have scripts to process these data

**Comment by lekoenig** [comment]
That sounds like a good plan, @jds485. Updating this issue:

- [ ] For now, start by bringing in processed NADP Cl, Mg, and Ca data from NHD MasterList data set

We can revisit processing of the raw NADP data as our modeling needs progress.

**Comment by msleckman** [comment]
> Just noting that these have been processed to NHD reaches for Cl, Mg, and Ca. Starting there could be simpler than having to start from the raw rasters. And someone (Mike?, Andrew?) must have scripts to process these data

Yes @jds485, pulling from here. https://www.sciencebase.gov/catalog/item/57e2ac2fe4b0908250045981

Xwalk to PRMS will be part of initial processing here, as the data is structured with a COMIDs as row indices. 

There is a data table per year here from 1987 to 2010. Do we want all of it?

**Comment by jds485** [comment]
Yes, I think it's best to pull every year. We'll have to create static features for these variables, so from Lauren's 1st post in this issue:
> - Assess interannual variability of Cl and Na deposition rates in DRB
> - If little interannual variability, decide whether to pull most recent NADP values, for example, or to average all years to come up with average deposition rates for Cl and Na

I'm not sure if Na is part of this dataset, and that's okay if it's unavailable.

**Comment by jds485** [comment]
Can this be closed?

**Comment by msleckman** [comment]
Yes closed. 
Note that the NADP data in our pipeline is current at target: `p2_NADP_Data` with a table that is by COMID 

```
    COMID CAT_DEP_CA CAT_DEP_NO3 CAT_DEP_SO4 CAT_DEP_N CAT_DEP_MG CAT_DEP_NH4 CAT_DEP_CL CAT_NADP_NODATA Year
1  2588313       1.14       10.73        8.75      4.96       0.26        3.08       1.94               0 2012
2  1750653       0.78       18.47       25.06      6.42       0.17        2.90       1.82               0 1994
3  4186517       1.24       10.10        9.01      6.30       0.29        5.18       1.90               0 2013
4  4494432       1.27       14.13       21.64      6.57       0.51        4.36       6.33               0 2007
5  4185459       0.90       20.55       27.42      6.75       0.28        2.71       2.90               0 1993
6  4780769       1.04       10.65       13.44      5.17       0.48        3.56       6.37               0 2009
7  4778901       1.07       19.14       24.49      6.71       0.21        3.08       2.02               0 1998
8  4496484       1.19       12.88       19.66      5.82       0.67        3.75       9.08               0 2007
9  9483454   -9999.00        8.06       11.56      3.99       1.43        2.80      20.67               0 2010
10 1748563       0.63        8.18        9.16      3.37       0.15        1.96       1.65               0 2009

```
New Issue to xwalk these comid to PRMS id
