### ISSUE TITLE
Gather monthly natural baseflow data for DRB

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#43]
Download monthly estimates of natural baseflow referenced to NHDPlusV2 reaches from ScienceBase (target 1980-2015): https://www.sciencebase.gov/catalog/item/6023e628d34e31ed20c874e4

**Comment by jds485** [comment]
Because this dataset does not cover 2015-present, I was thinking its value for modeling depends on how much interannual variability there is for each month. Here are 2 possible uses:

1. We could treat it as a static feature instead of a dynamic one. To make it static, monthly averages could be computed over the 35 years. 
2. Alternatively, we could use it as a dynamic monthly feature and fill in the 2016-present data with the monthly averages from the last 35 years.

**Comment by lekoenig** [comment]
The monthly estimates of natural baseflow are referenced to NHDPlusV2 reaches within the DRB. There are a few decision points for processing:

**1. NHD-to-PRMS translation**
Currently, I grab the values from the COMID's that represent the downstream ends of each PRMS segment. In doing so I assume that the monthly average baseflow for that COMID applies across the extent of the PRMS reach. However, some PRMS segments are comprised of multiple NHDPlusV2 reaches, so alternatively we could also take an average of the COMID-level baseflow estimates for all COMIDs that intersect a given PRMS segment.  

**2. Summary stats of interest**
This dataset contains four summary statistics for each month/year, including the mean and median predicted monthly baseflow from a random forest ensemble of 1000 predictions as well as the 10th and 90th percentiles of those predictions. I currently focus on the mean values but we could also retain all four values. Could the median/10th percentile/90th percentile predictions of monthly baseflow be useful as additional features?

**3. Static vs dynamic monthly feature**
In the interest of time, I suggest we forego running the random forest model to predict values for 2016-present, at least for now. Therefore, we could either compute monthly averages for the last 35 years, or use the baseflow estimates as a dynamic feature.

> We could treat it as a static feature instead of a dynamic one. To make it static, monthly averages could be computed over the 35 years.

It looks like there's a decent amount of interannual variability in the (mean predictions of) monthly natural baseflow. Here's an example for one 5th order reach that intersects our PRMS network:

![interannual_variation](https://user-images.githubusercontent.com/8785034/151071543-18becc20-a0f1-4fbd-87f4-38a6a9799c1b.png)

Distribution of the CV of the monthly averages across 455 reaches representing the PRMS network suggests that some months might have relatively more interannual variability than others:

![CV](https://user-images.githubusercontent.com/8785034/151073796-1aae7b59-f0c7-450b-abca-f415d11576a3.png)

@jds485 Do you have thoughts or preferences on any these processing steps?

**Comment by lekoenig** [comment]
Thanks, @jds485, this all sounds good to me!
