### ISSUE TITLE
Gridmet: Run gridmet tools with drb PRMS reaches shp

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#48]
translate gridded dataset to the specified vector aoi (polygons or polylines) using grid2shp_xagg package. 
1. Extract gridmet data 
2. re-grid to the defined aoi boundary 
3. Export as Netcdf

This will be conducted for the following gridmet variables: 
* Max and min temperature
* precipitation accumulation
* downward surface shortwave radiation 
* wind-velocity
* humidity (maximum and minimum relative humidity and specific humidity)

Repo: https://github.com/USGS-R/drb_gridmet_tools

**Comment by jzwart** [comment]
For the temperature forecasting project, we need the capability of matching grids to polylines and points as well. The REAME of the linked repo says `grid to hru polygon`, but could this be expanded to `HRU polygons, segment polylines, and points of interest` ?

**Comment by jds485** [comment]
> Interpolated PRMS

Are the PRMS HRUs being interpolated somehow? Or is this supposed to be a climate dataset (gridMET?) instead of PRMS?

**Comment by msleckman** [comment]
>For the temperature forecasting project, we need the capability of matching grids to polylines and points as well. The REAME of the linked repo says grid to hru polygon, but could this be expanded to HRU polygons, segment polylines, and points of interest 

@jzwart Thanks for specifying this. Yes, I will update the readme.
@jds485 I am definitely misusing the term 😄 . I'll update, and do let me know if it doesn't describes the process as it should.

**Comment by msleckman** [comment]
UPDATE: 

Gridmet pulled and processed for our catchments here [repo drb_gridmet_tools](https://github.com/USGS-R/drb_gridmet_tools/tree/gridmet_processing_v1)

Processing time to get all our variables of interest is ~1:30 min 😨 , for me today. (has run faster previously, so might be need to test in new env.)

Code branch `branch:Gridmet_processing_v1` to be merged to main after cleaning repo. [Issue #2](https://github.com/USGS-R/drb_gridmet_tools/issues/3) to resolve 

Questions: 
* Do we want to integrate `gridmet_split_script.py` into R targets pipeline and use `reticulate`? Will take a long time to build
* Should we load the gridmet output directly from  `1_fetch/in/`. Note that the output is too large to be stored in our github repo?

**Comment by jds485** [comment]
I think it's okay to keep the gridmet processing separate from our pipeline. We can save the gridmet data to S3 and read that into our pipeline as a target (similar to the ScienceBase targets)

**Comment by msleckman** [comment]
Alright, I'll share with you via teams the sample of the file so we can determine how to fetch, munge, process.

**Comment by msleckman** [comment]
UPDATE: 
gridmet_split_script.py merged to main in [repo drb_gridmet_tools](https://github.com/USGS-R/drb_gridmet_tools/tree/gridmet_processing_v1) 
[Issue #3](https://github.com/USGS-R/drb_gridmet_tools/issues/4) to resolve. 

Passed to @jsadler2 for further processing of data for drb-inland-salinity-ml that can then be added to pipeline.
