### ISSUE TITLE
Remove print statements

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#49]
Can we remove this print in [get_nlcd_LC.R](https://github.com/USGS-R/drb-inland-salinity-ml/blob/1b711919557ba6026d1d9a6dff95ee6ea049807a/1_fetch/src/get_nlcd_LC.R#L95)?
`print(list_out_paths)` 

And add quiet=TRUE in `st_read` statements in [1_fetch.R](https://github.com/USGS-R/drb-inland-salinity-ml/blob/1b711919557ba6026d1d9a6dff95ee6ea049807a/1_fetch.R#L90). Example:
`st_read(p1_reaches_shp)`

[1st line](https://github.com/USGS-R/drb-inland-salinity-ml/blob/1b711919557ba6026d1d9a6dff95ee6ea049807a/1_fetch.R#L90)
[2nd line](https://github.com/USGS-R/drb-inland-salinity-ml/blob/1b711919557ba6026d1d9a6dff95ee6ea049807a/1_fetch.R#L109)

**Comment by lekoenig** [comment]
I can add the `quiet=TRUE` argument to those calls to `st_read`. @msleckman, do you mind confirming whether it's OK to remove `print(list_out_paths)` in the `get_nlcd_LC` function, or whether it's useful to retain?

**Comment by msleckman** [comment]
Yes,`print()` statements can be removed
