### ISSUE TITLE
Fetch NHD attributes : NLCD Land Cover 2001-2019

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#56]
Adapt and expand NLCD 2011 fetch and processing functions (#28) to get all NLCD Land Cover Datasets with the relevant nhd attributes.

sb source: https://www.sciencebase.gov/catalog/item/5d66b3b6e4b0c4f70cefb11d

**Comment by jds485** [comment]
> I wonder if there's been a change in how the NLCD rasters get processed? If so, is that why we've opted to use the files on sharepoint instead of the most current ScienceBase release?

Yes, the rasters are processed differently in Andrew's pers. comm. files. I'm not sure what all of the differences are, but I know the changes were made to unify the approaches taken for all years. I'm not able to tag Andrew in this comment, but I can ask for details if you're interested

**Comment by lekoenig** [comment]
OK, thanks for this context @jds485. I don't need further details for now - knowing that there's a reason to use the local files answers my question and also serves to document in this issue why we opted to use the local files over the sb repo linked above.
