### ISSUE TITLE
Check 2017-present WQP data initially tagged as "preliminary"

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#6]
>Consideration of data tagged in WQP as "Preliminary"

Just to clarify, is the "preliminary" tag within the harmonized dataset? I'd expect that checks on those data would now be complete, so we could pull the current values for those samples labeled "preliminary".

For 2019-present data labeled as preliminary, I can see a few options:
1. We learn from the step above how much the preliminary vs. approved data differ. We base our decision to use preliminary or not from that analysis. 
2. We use/do not use preliminary data following the same guidelines as used for harmonization.
3. We do not use preliminary data for data quality concerns. If there are few preliminary samples, this can be a good option.

_Originally posted by @jds485 in https://github.com/USGS-R/drb-inland-salinity-ml/issues/3#issuecomment-953928129_

**Comment by jds485** [comment]
Update based on figures in #3 and #19, there are many preliminary data 2000-present, and data from ~2020 - present have provisional labels per USGS practice for newly collected data. So, option 3 on this list is not going to work for this project.

**Comment by lekoenig** [comment]
We currently use approach 2 on the list above and rely on the flags generated during data harmonization when it comes to filtering sites, since the figures in #3 show that a substantial chunk of data initially tagged as 'preliminary' in WQP is never revisited and approved. I'm going to close this issue for now.
