### ISSUE TITLE
Implement parallelization option

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#64]
Some targets take >20 mins to build. It would help to add tar_future or tar_clustermq parallelization options. 

I think data download targets are not supposed to be run in parallel so that the servers are not overloaded with requests (please correct me if that's wrong). We can use the `deployment = 'main'` option within `tar_targets` to force downloads to happen on the main core. Also open to alternative methods to using targets (e.g., force the download to happen with 1 worker instead of on main)

**Comment by jzwart** [comment]
Depends on where you're downloading from. Probably would not parallelize targets that are downloaded from NWIS, but you might be able to do so for something like AWS, but also be careful to not get IP blocked with too many repeated calls. 

`deployment = 'main'` is good. 
Also add in 
```
options(clustermq.scheduler = "multicore")
```
to the main `_targets.R` file. Then you should just be able to run `tar_make_clustermq(workers = #of workers you want)` and it will parallelize your targets

**Comment by lekoenig** [comment]
For our reference, [here's](http://internal.wma.chs.usgs.gov/dsp-manual/docs/tutorials/simple_targets_parallelization/) an internal doc Jesse Ross put together on simple parallelization of targets pipelines ✨

**Comment by jds485** [comment]
Thanks! I'm assigning myself to this issue because I've been working on parallel targets for the FHWA repo, too
