### ISSUE TITLE
Remove NLCD11_12 in standardization of raster classes for LC.

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#71]
Now that there is an issue/PR devoted to combining and/or renaming some of the land use categories across datasets, I wonder if omitting `NLCD11_12` should be done within that step of the pipeline? I'm not very familiar with what that step will look like though, so I leave that up to you.

_Originally posted by @lekoenig in https://github.com/USGS-R/drb-inland-salinity-ml/pull/38#discussion_r795717688_

**Comment by jds485** [comment]
@msleckman I think this has been addressed in #81. Is that right? If so, you can link the PR to this issue.

**Comment by msleckman** [comment]
Yes, this was resolved in #81 because the NLCD LC class reclassification table converted NLCD 12 class into NA.
