### ISSUE TITLE
Combine Rd Salt Data and scale to PRMS level

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#74]
From the list of annual Rd salt dfs, create a single aggregated df with all years and a additional column per catchment that calculates: sum of salt accumulation for every year in catchment / salt accumulation across DRB

**Comment by jds485** [comment]
@msleckman I thought the road salt PR addressed this, but maybe not fully? If there's more to address, can you add a comment to this issue with the remaining tasks?

**Comment by msleckman** [comment]
Yes it did.  Final target `p2_rdsalt_per_catchment_allyrs`
