### ISSUE TITLE
Xwalk p2_NADP_Data + clean

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#83]
Following #42 

xwalk  p2_NADP_Data from comid to PRMS segids. We should also clean (fix -9999) and remove measurements we do not need.

**Comment by jds485** [comment]
It might be cleaner to include the NADP fetch and process within `p1_vars_of_interest`. We can compute the average of annual deposition values using a similar approach as was used for the average of monthly precipitation variables.

**Comment by msleckman** [comment]
**Quick update on to do for p2_NADP_Data:**
* Aggregate from Comid to PRMS using x-walk process 
* clean - change NAs (-9999) and and possible rounding
* Keep attributes TOT and ACC -
  *  in the code block for p2_NADP_Data in `2_process.R` changed `select(COMID | starts_with('CAT')) %>%` to `select(COMID | starts_with(c('CAT','TOT','ACC')) %>%`
  * Or split the target such that we have 3 targets for NADP - `p2_NADP_Data_cat`, `p2_NADP_Data_tot`, `p2_NADP_Data_acc`
