### ISSUE TITLE
Gather TOT-level NHDV2 attribute variables for each reach

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#85]
For each PRMS segment, use `comid_down` from the xwalk table to gather the total upstream attribute values, using either TOT or ACC.

I think the following processing steps from #80 also apply here:

- [x] For PPT_MMMYYYY variables (50 years of average monthly precip), only use years 1971-2000 to compute the monthly averages to match the 30-year annual precip timeframe and the timeframe for all other meteorological variables. See comment from Jared https://github.com/USGS-R/drb-inland-salinity-ml/pull/73#discussion_r798995546.
- [x] For all variables, check for weird flag values (e.g. -9999) and replace with NA
- [x] I wonder if we'll want to output a summary table that contains min/max/number of non-NA values for each variable that we'll pass along to the modeling steps?

**Comment by jds485** [comment]
> output a summary table that contains min/max/number of non-NA values for each variable

Yes, that would be helpful if provided for each PRMS segment.
