### ISSUE TITLE
Move PRMS-NHDv2 xwalk out of salinity repo

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-inland-salinity-ml#86]
Move NHGFv1-NHDv2 xwalk out of salinity repo and instead manually add as an input dataset in 1_fetch/in

**Comment by jds485** [comment]
Adding tasks:
- [ ] Remove source code for crosswalk that is now located in [drb-network-prep](https://github.com/USGS-R/drb-network-prep.
- [ ] Read in crosswalk table from drb-network-prep
