### ISSUE TITLE
Load gridMET data into pipeline

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-inland-salinity-ml#87]

**Comment by msleckman** [comment]
Data has been converted from ncdf to df using raster pkg. Path: `Data/Data - Inland/gridMET/gridmet_drb.csv`

![image](https://user-images.githubusercontent.com/36547359/154733112-186ff3c3-4785-49e7-a19f-0577f60997c6.png)

**Comment by msleckman** [comment]
Updated with new catchment shapefile. 
Creating pull request by end of week.

**Comment by msleckman** [comment]
### Reticulate and Conda Environment

The env for python scripts is defined by a environment.yml file that creates the conda environment.

Seems we need to use `reticulate::conda_create()` or `reticulate::condaenv()` to set environment. 

Currently this does not work for me locally. FOr example, pandas library is not found in R using reticulate while it is define in env and py scripts run successful in python IDE and shell.

**Comment by lekoenig** [comment]
Do you need to call `import("pandas")` within the R script? I wonder if there's some useful insight in the reticulate docs for python packages [here](https://rstudio.github.io/reticulate/articles/python_packages.html).
